name: 'Conventional Commit PR Title Validator'
description: 'Validates Pull Request titles according to Conventional Commits specification'
author: 'lab42'
inputs:
  type:
    description: 'Regular expression pattern for commit type'
    required: false
    default: 'build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test'
  topic:
    description: 'Regular expression pattern for commit topic'
    required: false
    default: '(\([a-zA-Z0-9\-\.]+\))?(!)?'
  message:
    description: 'Regular expression pattern for commit message'
    required: false
    default: ' .*'
  pr_title:
    description: 'The Pull Request title to validate'
    required: true
runs:
  using: 'docker'
  image: 'docker://ghcr.io/lab42/ccu:latest'
  env:
    CCU_TYPE: ${{ inputs.type }}
    CCU_TOPIC: ${{ inputs.topic }}
    CCU_MESSAGE: ${{ inputs.message }}
    CCU_INPUT: ${{ inputs.pr_title }}
